import { FundData } from '../models/fund-data.model';

export const MOCK_FUND_DATA: FundData[] = [
  {
    date: '2023-10-01',
    fundName: 'Global Equity Fund',
    portfolioManagers: [
      {
        name: 'Alice Smith',
        detail:
          'Alice Smith\nLead Portfolio Manager\nTenure: 8 years\nExperience: 15 years in global equity markets\nBased in: New York, USA\nEducation: MBA, Harvard Business School',
      },
      {
        name: 'Bob Johnson',
        detail:
          'Bob Johnson\nCo-Portfolio Manager\nTenure: 5 years\nExperience: 10 years in investment management\nBased in: London, UK\nEducation: MSc Finance, London School of Economics',
      },
    ],
    investmentApproach:
      'Our investment approach focuses on long-term capital growth by identifying innovative companies with sustainable competitive advantages. We emphasize technology and disruptive sectors, using rigorous fundamental analysis and ESG integration. Active management and global diversification help us capture opportunities and manage risk in a rapidly evolving market environment.',
    overview: `The Global Equity Fund provides investors with access to a diversified portfolio of high-quality global equities, emphasizing companies driving innovation and shaping the future. Our philosophy centers on identifying businesses with robust financial health, strong management, and sustainable competitive advantages. We focus on long-term growth, particularly in technology, to deliver superior returns while managing risk. The fund’s strategy involves thorough research into company financials, industry trends, and macroeconomic factors. We invest in both established leaders and emerging disruptors, diversifying across sectors and geographies to mitigate risk and capture growth. ESG considerations are integrated into our process, ensuring responsible investing aligned with our clients’ values. Our experienced team maintains a disciplined process and adapts to changing markets, aiming to provide consistent results and transparent communication. The Global Equity Fund is a compelling choice for investors seeking long-term capital appreciation in a dynamic global marketplace.`,
    noStocks: '50',
    stockLimit: '10%',
    sectorLimit: '20%',
    countryLimit: '30%',
    riskActiveMoney: '5%',
    riskTrackError: '2%',
    minMarketCap: '$1B',
    turnover: '30%',
    cash: '5%',
    morningstarStyle: 'Growth',
    launchDate: '2010-01-01',
    comparativeIndex: 'MSCI World Index',
    sector: 'Technology',
    fundStructure: 'Open-ended',
    fundSize: '$500M',
    ocf: '1.5%',
    isin: 'US1234567890',
    sendol: 'USD',
    fundPerformance: `Over the past five years, the Global Equity Fund has delivered an impressive 15% annualized return, consistently outperforming its benchmark, the MSCI World Index. This strong performance is a testament to our disciplined investment process, which emphasizes thorough research, active management, and a focus on high-quality, innovative companies. Even during periods of heightened market volatility, the fund has demonstrated resilience, maintaining robust returns and protecting investor capital. Our approach to portfolio construction—balancing established industry leaders with promising up-and-comers—has enabled us to capture upside potential while managing downside risk. The fund’s diversified exposure across sectors and geographies has further contributed to its stability and performance, allowing us to capitalize on growth opportunities wherever they arise. We have also maintained a prudent risk management framework, with active monitoring of portfolio risk metrics such as tracking error and active money. In addition to strong absolute returns, the fund has delivered superior risk-adjusted performance, as evidenced by its Sharpe ratio and other key metrics. Our commitment to ESG integration has also resonated with investors, attracting significant inflows and contributing to the fund’s growth in assets under management. Over the past decade, the Global Equity Fund has demonstrated its ability to adapt to changing market conditions, seize emerging opportunities, and deliver value to investors. We remain focused on sustaining this track record of excellence and continuing to provide attractive returns for our clients in the years ahead.`,
    fundPositioning: `The Global Equity Fund is strategically positioned to capitalize on the most compelling trends shaping the global economy, with a particular focus on technology-driven innovation. Our portfolio managers maintain a forward-looking investment strategy, targeting companies at the forefront of transformative developments such as artificial intelligence, cloud computing, digital transformation, and sustainable technologies. This approach enables us to identify businesses with sustainable competitive advantages and strong growth prospects. We employ a rigorous fundamental analysis process, evaluating each company’s financial health, management quality, and long-term strategic vision. Our portfolio is balanced between established market leaders—who provide stability and consistent performance—and emerging innovators, which offer significant upside potential. This blend allows us to participate in the growth of mature companies while also capturing opportunities in rapidly evolving sectors. Geographic and sector diversification are key pillars of our positioning, helping to mitigate risk and enhance returns. We maintain exposure to both developed and emerging markets, ensuring that the fund benefits from global growth drivers. ESG considerations are fully integrated into our investment decisions, reflecting our commitment to responsible investing and long-term value creation. Active management is central to our approach, allowing us to respond quickly to changing market conditions and capitalize on new opportunities as they arise. We continuously monitor portfolio holdings and adjust allocations to reflect our latest research and market outlook. Our goal is to deliver superior risk-adjusted returns over the long term, making the Global Equity Fund a compelling choice for investors seeking growth, innovation, and resilience in their portfolios.`,
  },
  {
    date: '2023-09-15',
    fundName: 'Emerging Markets Growth Fund',
    portfolioManagers: [
      {
        name: 'Carlos Mendes',
        detail:
          'Carlos Mendes\nLead Portfolio Manager\nTenure: 10 years\nExperience: 18 years in emerging markets\nBased in: São Paulo, Brazil\nEducation: MBA, INSEAD',
      },
      {
        name: 'Priya Patel',
        detail:
          'Priya Patel\nCo-Portfolio Manager\nTenure: 6 years\nExperience: 12 years in global equities\nBased in: Mumbai, India\nEducation: CFA, MSc Economics, University of Mumbai',
      },
    ],
    investmentApproach:
      'We focus on high-growth companies in emerging economies, emphasizing sectors like consumer goods, technology, and financials. Our approach combines top-down macroeconomic analysis with bottom-up stock selection, leveraging local expertise and ESG integration to identify attractive opportunities and manage risks in dynamic markets.',
    overview: `The Emerging Markets Growth Fund is designed to capture the dynamic growth potential of emerging economies by investing in companies poised for expansion. Our strategy emphasizes sectors such as consumer goods, technology, and financials, where demographic trends and economic reforms are driving rapid change. We combine macroeconomic analysis with bottom-up stock selection to identify the most attractive opportunities across Asia, Latin America, and EMEA. The fund is managed by a team with deep local expertise, allowing us to navigate volatility and capitalize on secular growth trends. We maintain a diversified portfolio, balancing exposure to established leaders and emerging innovators. ESG integration is central to our process, ensuring responsible investing and long-term value creation. The Emerging Markets Growth Fund is suitable for investors seeking exposure to high-growth regions and companies benefiting from transformative economic shifts.`,
    noStocks: '60',
    stockLimit: '8%',
    sectorLimit: '18%',
    countryLimit: '25%',
    riskActiveMoney: '6%',
    riskTrackError: '2.5%',
    minMarketCap: '$500M',
    turnover: '40%',
    cash: '7%',
    morningstarStyle: 'Growth',
    launchDate: '2012-06-01',
    comparativeIndex: 'MSCI Emerging Markets Index',
    sector: 'Multi-sector',
    fundStructure: 'Open-ended',
    fundSize: '$350M',
    ocf: '1.8%',
    isin: 'LU2345678901',
    sendol: 'USD',
    fundPerformance: `The Emerging Markets Growth Fund has achieved a 12% annualized return over the last five years, outperforming its benchmark in most periods. Our disciplined approach and local expertise have enabled us to navigate volatility and capitalize on secular growth trends in emerging markets. The fund’s performance is driven by a combination of top-down macroeconomic analysis and bottom-up stock selection, allowing us to identify companies with strong growth prospects and resilient business models. We have maintained a diversified portfolio, balancing exposure to established leaders and emerging innovators across Asia, Latin America, and EMEA. Our active risk management framework, including ongoing monitoring of portfolio risk metrics, has helped us manage downside risk and preserve capital during periods of market turbulence. ESG integration is a key component of our investment process, ensuring that we invest responsibly and align with the values of our investors. The fund’s strong track record has attracted significant inflows, contributing to growth in assets under management. We remain committed to delivering superior risk-adjusted returns and adapting our strategy to evolving market conditions, making the Emerging Markets Growth Fund a compelling choice for investors seeking exposure to high-growth regions.`,
    fundPositioning: `We maintain a diversified portfolio with a tilt towards technology and consumer sectors, reflecting the rising middle class and digital adoption in emerging economies. Our positioning is informed by a combination of macroeconomic analysis and local market insights, allowing us to identify companies with strong growth potential and sustainable business models. We actively manage sector and country exposures to capture opportunities and mitigate risks, with a focus on companies benefiting from demographic trends, economic reforms, and technological innovation. ESG integration is central to our process, ensuring responsible investing and long-term value creation. We overweight sectors such as technology, consumer goods, and financials, while maintaining selective exposure to healthcare and industrials. Our portfolio is balanced between established market leaders and emerging innovators, providing stability and upside potential. Active risk management and ongoing monitoring of portfolio holdings enable us to respond quickly to changing market conditions and capitalize on new opportunities. The Emerging Markets Growth Fund is well-positioned to benefit from the continued growth and transformation of emerging economies, offering investors access to some of the world’s most dynamic markets.`,
  },
  {
    date: '2023-08-20',
    fundName: 'Sustainable Future Fund',
    portfolioManagers: [
      {
        name: 'Emma Lee',
        detail:
          'Emma Lee\nLead Portfolio Manager\nTenure: 7 years\nExperience: 14 years in sustainable investing\nBased in: Sydney, Australia\nEducation: MSc Environmental Science, University of Sydney',
      },
    ],
    investmentApproach:
      'We invest in companies with strong ESG credentials and sustainable business models, focusing on renewable energy, clean technology, and robust corporate governance. Our approach combines sector diversification, fundamental analysis, and active engagement to drive long-term value and positive environmental and social impact.',
    overview: `The Sustainable Future Fund targets companies that are leaders in environmental, social, and governance practices. We believe that sustainable business models drive long-term value creation and risk mitigation. The fund invests across sectors, with a preference for renewable energy, clean technology, and companies with strong corporate governance. Our disciplined investment process integrates ESG analysis at every stage, ensuring that our portfolio aligns with the values of our investors. We seek to identify businesses that are well-positioned to benefit from the global transition to a more sustainable economy. The fund is managed by an experienced team with deep expertise in sustainable investing, providing investors with access to high-quality opportunities in this rapidly evolving space. The Sustainable Future Fund is ideal for investors seeking to combine financial returns with positive environmental and social outcomes.`,
    noStocks: '40',
    stockLimit: '12%',
    sectorLimit: '22%',
    countryLimit: '28%',
    riskActiveMoney: '4%',
    riskTrackError: '1.8%',
    minMarketCap: '$750M',
    turnover: '25%',
    cash: '6%',
    morningstarStyle: 'Blend',
    launchDate: '2015-03-15',
    comparativeIndex: 'MSCI ACWI ESG Leaders Index',
    sector: 'Sustainable',
    fundStructure: 'Open-ended',
    fundSize: '$200M',
    ocf: '1.3%',
    isin: 'IE3456789012',
    sendol: 'USD',
    fundPerformance: `The Sustainable Future Fund has delivered a 10% annualized return since inception, with lower volatility than the broader market. Our ESG focus has attracted strong inflows and contributed to consistent outperformance. The fund’s performance is driven by a disciplined investment process that integrates ESG analysis at every stage, from idea generation to portfolio construction and ongoing monitoring. We invest in companies that are leaders in environmental stewardship, social responsibility, and corporate governance, believing that these factors contribute to long-term value creation and risk mitigation. Our portfolio is diversified across sectors and geographies, with a preference for renewable energy, clean technology, and companies with strong corporate governance. Active engagement with portfolio companies is a key part of our stewardship, enabling us to influence positive change and enhance long-term returns. The fund’s strong track record has attracted significant inflows, contributing to growth in assets under management. We remain committed to delivering superior risk-adjusted returns and positive environmental and social outcomes for our investors.`,
    fundPositioning: `We overweight renewable energy and technology sectors, and underweight industries with high carbon footprints. Our portfolio is constructed to capture opportunities in companies that are well-positioned to benefit from the global transition to a more sustainable economy. We maintain a diversified portfolio across sectors and geographies, with a focus on companies that demonstrate strong ESG credentials and sustainable business models. Active engagement with portfolio companies is a key part of our stewardship, enabling us to influence positive change and enhance long-term returns. We continuously monitor portfolio holdings and adjust allocations to reflect our latest research and market outlook. ESG integration is central to our process, ensuring responsible investing and long-term value creation. The Sustainable Future Fund is well-positioned to benefit from the continued growth and transformation of the global economy, offering investors access to high-quality opportunities in this rapidly evolving space.`,
  },
  {
    date: '2023-07-10',
    fundName: 'Global Bond Opportunities Fund',
    portfolioManagers: [
      {
        name: 'Michael Chen',
        detail:
          'Michael Chen\nLead Portfolio Manager\nTenure: 12 years\nExperience: 20 years in fixed income\nBased in: Hong Kong\nEducation: PhD Economics, University of Hong Kong',
      },
    ],
    investmentApproach:
      'We employ a flexible, unconstrained approach to global fixed income markets, combining macroeconomic analysis with credit research. Our strategy includes active duration and currency management, seeking attractive risk-adjusted returns across government, corporate, and emerging market bonds.',
    overview: `The Global Bond Opportunities Fund seeks attractive risk-adjusted returns by investing across the global fixed income universe. We combine macroeconomic analysis with credit research to identify opportunities in government, corporate, and emerging market bonds. Active duration and currency management are key tools in our process. The fund is managed by an experienced team with deep expertise in global fixed income markets, enabling us to adapt to changing market conditions and capitalize on new opportunities. Our flexible mandate allows us to invest across sectors, regions, and credit qualities, providing diversification and resilience. The Global Bond Opportunities Fund is suitable for investors seeking income, capital preservation, and exposure to a broad range of fixed income assets.`,
    noStocks: 'N/A',
    stockLimit: 'N/A',
    sectorLimit: 'N/A',
    countryLimit: '35%',
    riskActiveMoney: '3%',
    riskTrackError: '1.2%',
    minMarketCap: 'N/A',
    turnover: '50%',
    cash: '10%',
    morningstarStyle: 'Fixed Income',
    launchDate: '2008-11-01',
    comparativeIndex: 'Bloomberg Global Aggregate Bond Index',
    sector: 'Fixed Income',
    fundStructure: 'Open-ended',
    fundSize: '$800M',
    ocf: '0.9%',
    isin: 'GB4567890123',
    sendol: 'USD',
    fundPerformance: `The Global Bond Opportunities Fund has delivered a 6% annualized return over the past decade, with a focus on capital preservation and income generation. Our flexible mandate allows us to adapt to changing market conditions and capitalize on new opportunities across the global fixed income universe. The fund’s performance is driven by a disciplined investment process that combines macroeconomic analysis with credit research, enabling us to identify attractive opportunities in government, corporate, and emerging market bonds. Active duration and currency management are key tools in our process, allowing us to manage interest rate risk and enhance returns. Our portfolio is diversified across sectors, regions, and credit qualities, providing resilience and stability. We maintain a prudent risk management framework, with ongoing monitoring of portfolio risk metrics and active management of exposures. The fund’s strong track record has attracted significant inflows, contributing to growth in assets under management. We remain committed to delivering superior risk-adjusted returns and capital preservation for our investors.`,
    fundPositioning: `We are currently overweight investment grade corporates and underweight government bonds, with selective exposure to emerging market debt. Our portfolio is constructed to capture opportunities across the global fixed income universe, balancing income generation with capital preservation. Active duration and currency management are central to our approach, enabling us to respond quickly to changing market conditions and manage interest rate risk. We maintain a diversified portfolio across sectors, regions, and credit qualities, providing resilience and stability. Our investment process combines macroeconomic analysis with credit research, allowing us to identify attractive opportunities and manage risks effectively. We continuously monitor portfolio holdings and adjust allocations to reflect our latest research and market outlook. The Global Bond Opportunities Fund is well-positioned to benefit from the continued evolution of global fixed income markets, offering investors access to a broad range of opportunities and superior risk-adjusted returns.`,
  },
  {
    date: '2023-06-05',
    fundName: 'US Dividend Leaders Fund',
    portfolioManagers: [
      {
        name: 'Sarah Thompson',
        detail:
          'Sarah Thompson\nLead Portfolio Manager\nTenure: 9 years\nExperience: 16 years in US equities\nBased in: Chicago, USA\nEducation: MBA, University of Chicago Booth',
      },
    ],
    investmentApproach:
      'We focus on high-quality US companies with strong and growing dividends, emphasizing financial strength, cash flow generation, and shareholder-friendly policies. Our diversified approach favors defensive sectors and seeks to deliver consistent income and capital appreciation.',
    overview: `The US Dividend Leaders Fund invests in established US companies with a track record of paying and growing dividends. Our approach emphasizes financial strength, cash flow generation, and shareholder-friendly policies. The fund is diversified across sectors, with a bias towards defensive industries such as consumer staples and healthcare. We seek to identify companies with sustainable dividend growth and strong fundamentals, providing investors with a reliable source of income and potential for capital appreciation. The fund is managed by an experienced team with deep expertise in US equities, ensuring disciplined portfolio construction and ongoing risk management. The US Dividend Leaders Fund is ideal for investors seeking income, stability, and long-term growth from high-quality US companies.`,
    noStocks: '35',
    stockLimit: '15%',
    sectorLimit: '25%',
    countryLimit: '100%',
    riskActiveMoney: '2%',
    riskTrackError: '1.0%',
    minMarketCap: '$2B',
    turnover: '20%',
    cash: '4%',
    morningstarStyle: 'Value',
    launchDate: '2014-09-01',
    comparativeIndex: 'S&P 500 Dividend Aristocrats',
    sector: 'Equity Income',
    fundStructure: 'Open-ended',
    fundSize: '$600M',
    ocf: '1.1%',
    isin: 'US5678901234',
    sendol: 'USD',
    fundPerformance: `The US Dividend Leaders Fund has delivered an 8% annualized return since inception, with lower drawdowns than the broader US equity market. Dividend growth has been a key driver of performance, supported by our focus on high-quality companies with strong fundamentals and sustainable business models. The fund’s performance is driven by disciplined stock selection, emphasizing financial strength, cash flow generation, and shareholder-friendly policies. Our diversified approach favors defensive sectors such as consumer staples and healthcare, providing stability and resilience during periods of market volatility. We maintain a prudent risk management framework, with ongoing monitoring of portfolio risk metrics and active management of exposures. The fund’s strong track record has attracted significant inflows, contributing to growth in assets under management. We remain committed to delivering consistent income and capital appreciation for our investors, making the US Dividend Leaders Fund a compelling choice for those seeking reliable returns from high-quality US companies.`,
    fundPositioning: `We overweight consumer staples and healthcare, and underweight cyclical sectors. The portfolio is constructed to provide a balance between income generation and capital appreciation, with a focus on companies that have a track record of paying and growing dividends. We maintain a diversified portfolio across sectors, with a bias towards defensive industries that offer stability and resilience during periods of market volatility. Our investment process emphasizes financial strength, cash flow generation, and shareholder-friendly policies, ensuring that our portfolio is comprised of high-quality companies with sustainable business models. The portfolio is rebalanced quarterly to maintain dividend quality and diversification, allowing us to respond to changing market conditions and capitalize on new opportunities. The US Dividend Leaders Fund is well-positioned to benefit from the continued growth of high-quality US companies, offering investors a reliable source of income and potential for long-term capital appreciation.`,
  },
];
